name: miNEMcraft
version: 1.0.0
main: com.github.planethouki.plugin.MinemcraftPlugin
author: planethouki
commands:
  mnc:
    description: todo
    usage:
      - /<command> balance
      - /<command> register
    default: true
  mncx:
    description: test command