name: miNEMcraft
version: 1.0.0
main: com.planethouki.plugin.MinemcraftPlugin
author: planethouki
commands:
  mnc:
    description: todo
    usage:
      - /<command> balance
      - /<command> register
    default: true
  mncd:
    description: debug command